img_size: [120, 160]
top_cutoff: 40

detector:
  - merganser_line_detector.LineDetectorHSV
  - configuration:
      kernel_size: 3
      large_kernel_size: 11

      hsv_white1:  [  0,   0, 150]
      hsv_white2:  [180,  50, 255]
      hsv_yellow1: [ 20, 140, 100]
      hsv_yellow2: [ 45, 255, 255]
      hsv_red1:    [  0, 140, 100]
      hsv_red2:    [ 15, 255, 255]
      hsv_red3:    [165, 140, 100]
      hsv_red4:    [180, 255, 255]
      hsv_black1:  [  0,   0,   0]
      hsv_black2:  [180, 255,  80]
