ARG ARCH=arm32v7
ARG MAJOR=daffy
ARG BASE_TAG=${MAJOR}-${ARCH}
ARG BASE_IMAGE=dt-core

# define base image
FROM duckietown/${BASE_IMAGE}:${BASE_TAG}

RUN apt-get update \
  && apt-get install -y --no-install-recommends cython \
  && rm -rf /var/lib/apt/lists/*

RUN pip install autograd scikit-image>=0.14.5

CMD ["bash", "-c", "${LAUNCHFILE}"]

LABEL maintainer="Tristan Deleu, Basile Dura"
